/**
 * generated by Xtext 2.10.0
 */
package pt.iscte.xdiagram.dsl;

import pt.iscte.xdiagram.dsl.XdiagramDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class XdiagramDslStandaloneSetup extends XdiagramDslStandaloneSetupGenerated {
  public static void doSetup() {
    XdiagramDslStandaloneSetup _xdiagramDslStandaloneSetup = new XdiagramDslStandaloneSetup();
    _xdiagramDslStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
