/**
 *
 * $Id$
 */
package conceptualmodel.validation;

import conceptualmodel.Attribute;
import conceptualmodel.Composite;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link conceptualmodel.Class}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ClassValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateAbstract(boolean value);
	boolean validateProperties(EList<Attribute> value);
	boolean validateSuperclass(conceptualmodel.Class value);
	boolean validateComposites(EList<Composite> value);
}
