/**
 *
 * $Id$
 */
package conceptualmodel.validation;

import conceptualmodel.Association;
import conceptualmodel.Attribute;
import conceptualmodel.Entity;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link conceptualmodel.Entity}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EntityValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateAbstract(boolean value);
	boolean validateAttributes(EList<Attribute> value);
	boolean validateExtends(Entity value);
	boolean validateAssociations(EList<Association> value);

	boolean validateRelations(EList<Association> value);
}
