/**
 * generated by Xtext 2.10.0
 */
package pt.iscte.xdiagram.dsl.model;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Arrow</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see pt.iscte.xdiagram.dsl.model.ModelPackage#getArrow()
 * @model
 * @generated
 */
public interface Arrow extends FeatureContainer
{
} // Arrow
