/**
 * generated by Xtext 2.10.0
 */
package pt.iscte.xdiagram.dsl.model;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Boolean Value</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link pt.iscte.xdiagram.dsl.model.BooleanValue#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see pt.iscte.xdiagram.dsl.model.ModelPackage#getBooleanValue()
 * @model
 * @generated
 */
public interface BooleanValue extends Value
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * The literals are from the enumeration {@link pt.iscte.xdiagram.dsl.model.BooleanLiteral}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see pt.iscte.xdiagram.dsl.model.BooleanLiteral
   * @see #setValue(BooleanLiteral)
   * @see pt.iscte.xdiagram.dsl.model.ModelPackage#getBooleanValue_Value()
   * @model
   * @generated
   */
  BooleanLiteral getValue();

  /**
   * Sets the value of the '{@link pt.iscte.xdiagram.dsl.model.BooleanValue#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see pt.iscte.xdiagram.dsl.model.BooleanLiteral
   * @see #getValue()
   * @generated
   */
  void setValue(BooleanLiteral value);

} // BooleanValue
