/**
 * generated by Xtext 2.10.0
 */
package pt.iscte.xdiagram.dsl.model;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Image</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link pt.iscte.xdiagram.dsl.model.Image#getImageId <em>Image Id</em>}</li>
 * </ul>
 *
 * @see pt.iscte.xdiagram.dsl.model.ModelPackage#getImage()
 * @model
 * @generated
 */
public interface Image extends ConnectableElement
{
  /**
   * Returns the value of the '<em><b>Image Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Image Id</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Image Id</em>' attribute.
   * @see #setImageId(String)
   * @see pt.iscte.xdiagram.dsl.model.ModelPackage#getImage_ImageId()
   * @model
   * @generated
   */
  String getImageId();

  /**
   * Sets the value of the '{@link pt.iscte.xdiagram.dsl.model.Image#getImageId <em>Image Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Image Id</em>' attribute.
   * @see #getImageId()
   * @generated
   */
  void setImageId(String value);

} // Image
