/**
 * generated by Xtext 2.10.0
 */
package pt.iscte.xdiagram.dsl.model;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Line Style</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link pt.iscte.xdiagram.dsl.model.LineStyle#getStyle <em>Style</em>}</li>
 *   <li>{@link pt.iscte.xdiagram.dsl.model.LineStyle#isManhattan <em>Manhattan</em>}</li>
 * </ul>
 *
 * @see pt.iscte.xdiagram.dsl.model.ModelPackage#getLineStyle()
 * @model
 * @generated
 */
public interface LineStyle extends Feature
{
  /**
   * Returns the value of the '<em><b>Style</b></em>' attribute.
   * The literals are from the enumeration {@link pt.iscte.xdiagram.dsl.model.LineType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Style</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Style</em>' attribute.
   * @see pt.iscte.xdiagram.dsl.model.LineType
   * @see #setStyle(LineType)
   * @see pt.iscte.xdiagram.dsl.model.ModelPackage#getLineStyle_Style()
   * @model
   * @generated
   */
  LineType getStyle();

  /**
   * Sets the value of the '{@link pt.iscte.xdiagram.dsl.model.LineStyle#getStyle <em>Style</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Style</em>' attribute.
   * @see pt.iscte.xdiagram.dsl.model.LineType
   * @see #getStyle()
   * @generated
   */
  void setStyle(LineType value);

  /**
   * Returns the value of the '<em><b>Manhattan</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Manhattan</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Manhattan</em>' attribute.
   * @see #setManhattan(boolean)
   * @see pt.iscte.xdiagram.dsl.model.ModelPackage#getLineStyle_Manhattan()
   * @model
   * @generated
   */
  boolean isManhattan();

  /**
   * Sets the value of the '{@link pt.iscte.xdiagram.dsl.model.LineStyle#isManhattan <em>Manhattan</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Manhattan</em>' attribute.
   * @see #isManhattan()
   * @generated
   */
  void setManhattan(boolean value);

} // LineStyle
