/**
 * generated by Xtext 2.10.0
 */
package pt.iscte.xdiagram.dsl.model;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Meta Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link pt.iscte.xdiagram.dsl.model.MetaModel#getPlugin <em>Plugin</em>}</li>
 *   <li>{@link pt.iscte.xdiagram.dsl.model.MetaModel#getEcorePath <em>Ecore Path</em>}</li>
 * </ul>
 *
 * @see pt.iscte.xdiagram.dsl.model.ModelPackage#getMetaModel()
 * @model
 * @generated
 */
public interface MetaModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Plugin</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Plugin</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Plugin</em>' attribute.
   * @see #setPlugin(String)
   * @see pt.iscte.xdiagram.dsl.model.ModelPackage#getMetaModel_Plugin()
   * @model
   * @generated
   */
  String getPlugin();

  /**
   * Sets the value of the '{@link pt.iscte.xdiagram.dsl.model.MetaModel#getPlugin <em>Plugin</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Plugin</em>' attribute.
   * @see #getPlugin()
   * @generated
   */
  void setPlugin(String value);

  /**
   * Returns the value of the '<em><b>Ecore Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ecore Path</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ecore Path</em>' attribute.
   * @see #setEcorePath(String)
   * @see pt.iscte.xdiagram.dsl.model.ModelPackage#getMetaModel_EcorePath()
   * @model
   * @generated
   */
  String getEcorePath();

  /**
   * Sets the value of the '{@link pt.iscte.xdiagram.dsl.model.MetaModel#getEcorePath <em>Ecore Path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ecore Path</em>' attribute.
   * @see #getEcorePath()
   * @generated
   */
  void setEcorePath(String value);

} // MetaModel
