/*
 * generated by Xtext
 */
package org.eclipselabs.xdiagram;

import org.eclipse.xtext.scoping.impl.ImportUriGlobalScopeProvider;
import org.eclipse.xtext.scoping.impl.ImportedNamespaceAwareLocalScopeProvider;
import org.eclipselabs.xdiagram.validation.DslValidator;
import org.eclipselabs.xdiagram.validation.XDiagramValidator;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DslRuntimeModule extends org.eclipselabs.xdiagram.AbstractDslRuntimeModule {

	public Class<? extends org.eclipse.xtext.scoping.IScopeProvider> bindIScopeProvider() {
		return ImportedNamespaceAwareLocalScopeProvider.class;
	}
	
	public Class<? extends org.eclipse.xtext.scoping.IGlobalScopeProvider> bindIGlobalScopeProvider() {
		return ImportUriGlobalScopeProvider.class;
	}
	
	@Override
	public Class<? extends DslValidator> bindDslValidator() {
		return XDiagramValidator.class;
	}
}
