/*
* generated by Xtext
*/
package org.eclipselabs.xdiagram.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.eclipselabs.xdiagram.services.DslGrammarAccess;

public class DslParser extends AbstractContentAssistParser {
	
	@Inject
	private DslGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.eclipselabs.xdiagram.ui.contentassist.antlr.internal.InternalDslParser createParser() {
		org.eclipselabs.xdiagram.ui.contentassist.antlr.internal.InternalDslParser result = new org.eclipselabs.xdiagram.ui.contentassist.antlr.internal.InternalDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getXDiagramAccess().getAlternatives_5(), "rule__XDiagram__Alternatives_5");
					put(grammarAccess.getDiagramElementAccess().getAlternatives(), "rule__DiagramElement__Alternatives");
					put(grammarAccess.getFeatureAccess().getAlternatives(), "rule__Feature__Alternatives");
					put(grammarAccess.getStyleFeatureAccess().getAlternatives(), "rule__StyleFeature__Alternatives");
					put(grammarAccess.getFeatureContainerAccess().getAlternatives(), "rule__FeatureContainer__Alternatives");
					put(grammarAccess.getLinkAccess().getAlternatives_1(), "rule__Link__Alternatives_1");
					put(grammarAccess.getLinkFeatureAccess().getAlternatives(), "rule__LinkFeature__Alternatives");
					put(grammarAccess.getDecoratorAccess().getAlternatives_0(), "rule__Decorator__Alternatives_0");
					put(grammarAccess.getDecoratorAccess().getAlternatives_1(), "rule__Decorator__Alternatives_1");
					put(grammarAccess.getStaticElementAccess().getAlternatives(), "rule__StaticElement__Alternatives");
					put(grammarAccess.getColorAccess().getAlternatives(), "rule__Color__Alternatives");
					put(grammarAccess.getConnectableElementAccess().getAlternatives(), "rule__ConnectableElement__Alternatives");
					put(grammarAccess.getConnectableElementFeatureAccess().getAlternatives(), "rule__ConnectableElementFeature__Alternatives");
					put(grammarAccess.getRectangleAccess().getAlternatives_1(), "rule__Rectangle__Alternatives_1");
					put(grammarAccess.getRectangleFeatureAccess().getAlternatives(), "rule__RectangleFeature__Alternatives");
					put(grammarAccess.getEllipseAccess().getAlternatives_1(), "rule__Ellipse__Alternatives_1");
					put(grammarAccess.getPolylineAccess().getAlternatives_1(), "rule__Polyline__Alternatives_1");
					put(grammarAccess.getValueAccess().getAlternatives(), "rule__Value__Alternatives");
					put(grammarAccess.getStringValueAccess().getAlternatives(), "rule__StringValue__Alternatives");
					put(grammarAccess.getFigureFeatureAccess().getAlternatives(), "rule__FigureFeature__Alternatives");
					put(grammarAccess.getLabelFeatureAccess().getAlternatives(), "rule__LabelFeature__Alternatives");
					put(grammarAccess.getImageFeatureAccess().getAlternatives(), "rule__ImageFeature__Alternatives");
					put(grammarAccess.getInvisibleFeatureAccess().getAlternatives(), "rule__InvisibleFeature__Alternatives");
					put(grammarAccess.getColorFeatureAccess().getAlternatives(), "rule__ColorFeature__Alternatives");
					put(grammarAccess.getTextValueAccess().getAlternatives_1(), "rule__TextValue__Alternatives_1");
					put(grammarAccess.getConnectionTypeAccess().getAlternatives(), "rule__ConnectionType__Alternatives");
					put(grammarAccess.getAnchorDirectionAccess().getAlternatives(), "rule__AnchorDirection__Alternatives");
					put(grammarAccess.getDefaultColorAccess().getAlternatives(), "rule__DefaultColor__Alternatives");
					put(grammarAccess.getContainerLayoutAccess().getAlternatives(), "rule__ContainerLayout__Alternatives");
					put(grammarAccess.getOperatorAccess().getAlternatives(), "rule__Operator__Alternatives");
					put(grammarAccess.getBooleanLiteralAccess().getAlternatives(), "rule__BooleanLiteral__Alternatives");
					put(grammarAccess.getFontFaceTypeAccess().getAlternatives(), "rule__FontFaceType__Alternatives");
					put(grammarAccess.getFontStyleTypeAccess().getAlternatives(), "rule__FontStyleType__Alternatives");
					put(grammarAccess.getLineTypeAccess().getAlternatives(), "rule__LineType__Alternatives");
					put(grammarAccess.getXDiagramAccess().getGroup(), "rule__XDiagram__Group__0");
					put(grammarAccess.getImportStatementAccess().getGroup(), "rule__ImportStatement__Group__0");
					put(grammarAccess.getImportStatementAccess().getGroup_1(), "rule__ImportStatement__Group_1__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
					put(grammarAccess.getQualifiedNameWithWildCardAccess().getGroup(), "rule__QualifiedNameWithWildCard__Group__0");
					put(grammarAccess.getQualifiedNameWithWildCardAccess().getGroup_1(), "rule__QualifiedNameWithWildCard__Group_1__0");
					put(grammarAccess.getStyleAccess().getGroup(), "rule__Style__Group__0");
					put(grammarAccess.getStyleAccess().getGroup_2(), "rule__Style__Group_2__0");
					put(grammarAccess.getFeatureConditionalAccess().getGroup(), "rule__FeatureConditional__Group__0");
					put(grammarAccess.getNodeAccess().getGroup(), "rule__Node__Group__0");
					put(grammarAccess.getNodeAccess().getGroup_3(), "rule__Node__Group_3__0");
					put(grammarAccess.getLinkAccess().getGroup(), "rule__Link__Group__0");
					put(grammarAccess.getLinkAccess().getGroup_1_1(), "rule__Link__Group_1_1__0");
					put(grammarAccess.getLinkAccess().getGroup_3(), "rule__Link__Group_3__0");
					put(grammarAccess.getLinkAccess().getGroup_7(), "rule__Link__Group_7__0");
					put(grammarAccess.getLinkAccess().getGroup_10(), "rule__Link__Group_10__0");
					put(grammarAccess.getDecoratorAccess().getGroup(), "rule__Decorator__Group__0");
					put(grammarAccess.getDecoratorAccess().getGroup_0_0(), "rule__Decorator__Group_0_0__0");
					put(grammarAccess.getAnchorAccess().getGroup(), "rule__Anchor__Group__0");
					put(grammarAccess.getCustomColorAccess().getGroup(), "rule__CustomColor__Group__0");
					put(grammarAccess.getRectangleAccess().getGroup(), "rule__Rectangle__Group__0");
					put(grammarAccess.getRectangleAccess().getGroup_2(), "rule__Rectangle__Group_2__0");
					put(grammarAccess.getRectangleAccess().getGroup_5(), "rule__Rectangle__Group_5__0");
					put(grammarAccess.getRhombusAccess().getGroup(), "rule__Rhombus__Group__0");
					put(grammarAccess.getRhombusAccess().getGroup_3(), "rule__Rhombus__Group_3__0");
					put(grammarAccess.getRhombusAccess().getGroup_6(), "rule__Rhombus__Group_6__0");
					put(grammarAccess.getEllipseAccess().getGroup(), "rule__Ellipse__Group__0");
					put(grammarAccess.getEllipseAccess().getGroup_2(), "rule__Ellipse__Group_2__0");
					put(grammarAccess.getEllipseAccess().getGroup_5(), "rule__Ellipse__Group_5__0");
					put(grammarAccess.getPolylineAccess().getGroup(), "rule__Polyline__Group__0");
					put(grammarAccess.getPolylineAccess().getGroup_2(), "rule__Polyline__Group_2__0");
					put(grammarAccess.getPolylineAccess().getGroup_8(), "rule__Polyline__Group_8__0");
					put(grammarAccess.getContainsAccess().getGroup(), "rule__Contains__Group__0");
					put(grammarAccess.getDoubleValueAccess().getGroup(), "rule__DoubleValue__Group__0");
					put(grammarAccess.getLabelAccess().getGroup(), "rule__Label__Group__0");
					put(grammarAccess.getLabelAccess().getGroup_3(), "rule__Label__Group_3__0");
					put(grammarAccess.getLabelAccess().getGroup_6(), "rule__Label__Group_6__0");
					put(grammarAccess.getImageAccess().getGroup(), "rule__Image__Group__0");
					put(grammarAccess.getImageAccess().getGroup_2(), "rule__Image__Group_2__0");
					put(grammarAccess.getImageAccess().getGroup_5(), "rule__Image__Group_5__0");
					put(grammarAccess.getInvisibleAccess().getGroup(), "rule__Invisible__Group__0");
					put(grammarAccess.getInvisibleAccess().getGroup_2(), "rule__Invisible__Group_2__0");
					put(grammarAccess.getInvisibleAccess().getGroup_5(), "rule__Invisible__Group_5__0");
					put(grammarAccess.getForegroundAccess().getGroup(), "rule__Foreground__Group__0");
					put(grammarAccess.getBackgroundAccess().getGroup(), "rule__Background__Group__0");
					put(grammarAccess.getTransparencyAccess().getGroup(), "rule__Transparency__Group__0");
					put(grammarAccess.getSizeAccess().getGroup(), "rule__Size__Group__0");
					put(grammarAccess.getPointAccess().getGroup(), "rule__Point__Group__0");
					put(grammarAccess.getPositionAccess().getGroup(), "rule__Position__Group__0");
					put(grammarAccess.getCornerAccess().getGroup(), "rule__Corner__Group__0");
					put(grammarAccess.getTextValueAccess().getGroup(), "rule__TextValue__Group__0");
					put(grammarAccess.getFontFaceAccess().getGroup(), "rule__FontFace__Group__0");
					put(grammarAccess.getFontSizeAccess().getGroup(), "rule__FontSize__Group__0");
					put(grammarAccess.getFontStyleAccess().getGroup(), "rule__FontStyle__Group__0");
					put(grammarAccess.getFontStyleAccess().getGroup_2(), "rule__FontStyle__Group_2__0");
					put(grammarAccess.getLineStyleAccess().getGroup(), "rule__LineStyle__Group__0");
					put(grammarAccess.getLineWidthAccess().getGroup(), "rule__LineWidth__Group__0");
					put(grammarAccess.getXDiagramAccess().getImportURIAssignment_1(), "rule__XDiagram__ImportURIAssignment_1");
					put(grammarAccess.getXDiagramAccess().getImportsAssignment_2(), "rule__XDiagram__ImportsAssignment_2");
					put(grammarAccess.getXDiagramAccess().getModelClassAssignment_4(), "rule__XDiagram__ModelClassAssignment_4");
					put(grammarAccess.getXDiagramAccess().getElementsAssignment_5_0(), "rule__XDiagram__ElementsAssignment_5_0");
					put(grammarAccess.getXDiagramAccess().getStylesAssignment_5_1(), "rule__XDiagram__StylesAssignment_5_1");
					put(grammarAccess.getXDiagramAccess().getColorsAssignment_5_2(), "rule__XDiagram__ColorsAssignment_5_2");
					put(grammarAccess.getImportStatementAccess().getImportedNamespaceAssignment_1_1(), "rule__ImportStatement__ImportedNamespaceAssignment_1_1");
					put(grammarAccess.getStyleAccess().getNameAssignment_1(), "rule__Style__NameAssignment_1");
					put(grammarAccess.getStyleAccess().getStyleAssignment_2_1(), "rule__Style__StyleAssignment_2_1");
					put(grammarAccess.getStyleAccess().getFeaturesAssignment_4(), "rule__Style__FeaturesAssignment_4");
					put(grammarAccess.getFeatureConditionalAccess().getModelAttributeAssignment_1(), "rule__FeatureConditional__ModelAttributeAssignment_1");
					put(grammarAccess.getFeatureConditionalAccess().getOperatorAssignment_2(), "rule__FeatureConditional__OperatorAssignment_2");
					put(grammarAccess.getFeatureConditionalAccess().getValueAssignment_3(), "rule__FeatureConditional__ValueAssignment_3");
					put(grammarAccess.getNodeAccess().getModelClassAssignment_1(), "rule__Node__ModelClassAssignment_1");
					put(grammarAccess.getNodeAccess().getToolNameAssignment_2(), "rule__Node__ToolNameAssignment_2");
					put(grammarAccess.getNodeAccess().getImageIdAssignment_3_1(), "rule__Node__ImageIdAssignment_3_1");
					put(grammarAccess.getNodeAccess().getRootFigureAssignment_5(), "rule__Node__RootFigureAssignment_5");
					put(grammarAccess.getLinkAccess().getModelReferenceAssignment_1_0(), "rule__Link__ModelReferenceAssignment_1_0");
					put(grammarAccess.getLinkAccess().getComplexAssignment_1_1_0(), "rule__Link__ComplexAssignment_1_1_0");
					put(grammarAccess.getLinkAccess().getModelClassAssignment_1_1_1(), "rule__Link__ModelClassAssignment_1_1_1");
					put(grammarAccess.getLinkAccess().getSourceReferenceAssignment_1_1_3(), "rule__Link__SourceReferenceAssignment_1_1_3");
					put(grammarAccess.getLinkAccess().getTargetReferenceAssignment_1_1_5(), "rule__Link__TargetReferenceAssignment_1_1_5");
					put(grammarAccess.getLinkAccess().getToolNameAssignment_2(), "rule__Link__ToolNameAssignment_2");
					put(grammarAccess.getLinkAccess().getImageIdAssignment_3_1(), "rule__Link__ImageIdAssignment_3_1");
					put(grammarAccess.getLinkAccess().getTypeAssignment_6(), "rule__Link__TypeAssignment_6");
					put(grammarAccess.getLinkAccess().getStyledAssignment_7_0(), "rule__Link__StyledAssignment_7_0");
					put(grammarAccess.getLinkAccess().getStyleAssignment_7_1(), "rule__Link__StyleAssignment_7_1");
					put(grammarAccess.getLinkAccess().getFeaturesAssignment_9(), "rule__Link__FeaturesAssignment_9");
					put(grammarAccess.getLinkAccess().getDecoratorsAssignment_10_1(), "rule__Link__DecoratorsAssignment_10_1");
					put(grammarAccess.getDecoratorAccess().getPositionAssignment_0_0_1(), "rule__Decorator__PositionAssignment_0_0_1");
					put(grammarAccess.getDecoratorAccess().getSourceAssignment_0_1(), "rule__Decorator__SourceAssignment_0_1");
					put(grammarAccess.getDecoratorAccess().getTargetAssignment_0_2(), "rule__Decorator__TargetAssignment_0_2");
					put(grammarAccess.getDecoratorAccess().getMiddleAssignment_0_3(), "rule__Decorator__MiddleAssignment_0_3");
					put(grammarAccess.getDecoratorAccess().getStaticElementAssignment_1_0(), "rule__Decorator__StaticElementAssignment_1_0");
					put(grammarAccess.getDecoratorAccess().getLabelAssignment_1_1(), "rule__Decorator__LabelAssignment_1_1");
					put(grammarAccess.getAnchorAccess().getDirectionAssignment_1(), "rule__Anchor__DirectionAssignment_1");
					put(grammarAccess.getAnchorAccess().getModelReferenceAssignment_2(), "rule__Anchor__ModelReferenceAssignment_2");
					put(grammarAccess.getAnchorAccess().getConditionalAssignment_3(), "rule__Anchor__ConditionalAssignment_3");
					put(grammarAccess.getCustomColorAccess().getNameAssignment_1(), "rule__CustomColor__NameAssignment_1");
					put(grammarAccess.getCustomColorAccess().getRAssignment_2(), "rule__CustomColor__RAssignment_2");
					put(grammarAccess.getCustomColorAccess().getGAssignment_4(), "rule__CustomColor__GAssignment_4");
					put(grammarAccess.getCustomColorAccess().getBAssignment_6(), "rule__CustomColor__BAssignment_6");
					put(grammarAccess.getColorAccess().getDefaultAssignment_0(), "rule__Color__DefaultAssignment_0");
					put(grammarAccess.getColorAccess().getCustomAssignment_1(), "rule__Color__CustomAssignment_1");
					put(grammarAccess.getRectangleAccess().getRectangleAssignment_1_0(), "rule__Rectangle__RectangleAssignment_1_0");
					put(grammarAccess.getRectangleAccess().getSquareAssignment_1_1(), "rule__Rectangle__SquareAssignment_1_1");
					put(grammarAccess.getRectangleAccess().getStyledAssignment_2_0(), "rule__Rectangle__StyledAssignment_2_0");
					put(grammarAccess.getRectangleAccess().getStyleAssignment_2_1(), "rule__Rectangle__StyleAssignment_2_1");
					put(grammarAccess.getRectangleAccess().getFeaturesAssignment_4(), "rule__Rectangle__FeaturesAssignment_4");
					put(grammarAccess.getRectangleAccess().getCompositeAssignment_5_0(), "rule__Rectangle__CompositeAssignment_5_0");
					put(grammarAccess.getRectangleAccess().getChildrenAssignment_5_1(), "rule__Rectangle__ChildrenAssignment_5_1");
					put(grammarAccess.getRhombusAccess().getStyledAssignment_3_0(), "rule__Rhombus__StyledAssignment_3_0");
					put(grammarAccess.getRhombusAccess().getStyleAssignment_3_1(), "rule__Rhombus__StyleAssignment_3_1");
					put(grammarAccess.getRhombusAccess().getFeaturesAssignment_5(), "rule__Rhombus__FeaturesAssignment_5");
					put(grammarAccess.getRhombusAccess().getCompositeAssignment_6_0(), "rule__Rhombus__CompositeAssignment_6_0");
					put(grammarAccess.getRhombusAccess().getChildrenAssignment_6_1(), "rule__Rhombus__ChildrenAssignment_6_1");
					put(grammarAccess.getEllipseAccess().getEllipseAssignment_1_0(), "rule__Ellipse__EllipseAssignment_1_0");
					put(grammarAccess.getEllipseAccess().getCircleAssignment_1_1(), "rule__Ellipse__CircleAssignment_1_1");
					put(grammarAccess.getEllipseAccess().getStyledAssignment_2_0(), "rule__Ellipse__StyledAssignment_2_0");
					put(grammarAccess.getEllipseAccess().getStyleAssignment_2_1(), "rule__Ellipse__StyleAssignment_2_1");
					put(grammarAccess.getEllipseAccess().getFeaturesAssignment_4(), "rule__Ellipse__FeaturesAssignment_4");
					put(grammarAccess.getEllipseAccess().getCompositeAssignment_5_0(), "rule__Ellipse__CompositeAssignment_5_0");
					put(grammarAccess.getEllipseAccess().getChildrenAssignment_5_1(), "rule__Ellipse__ChildrenAssignment_5_1");
					put(grammarAccess.getPolylineAccess().getPolygonAssignment_1_0(), "rule__Polyline__PolygonAssignment_1_0");
					put(grammarAccess.getPolylineAccess().getPolylineAssignment_1_1(), "rule__Polyline__PolylineAssignment_1_1");
					put(grammarAccess.getPolylineAccess().getStyledAssignment_2_0(), "rule__Polyline__StyledAssignment_2_0");
					put(grammarAccess.getPolylineAccess().getStyleAssignment_2_1(), "rule__Polyline__StyleAssignment_2_1");
					put(grammarAccess.getPolylineAccess().getFeaturesAssignment_4(), "rule__Polyline__FeaturesAssignment_4");
					put(grammarAccess.getPolylineAccess().getFeaturesAssignment_5(), "rule__Polyline__FeaturesAssignment_5");
					put(grammarAccess.getPolylineAccess().getFeaturesAssignment_6(), "rule__Polyline__FeaturesAssignment_6");
					put(grammarAccess.getPolylineAccess().getFeaturesAssignment_7(), "rule__Polyline__FeaturesAssignment_7");
					put(grammarAccess.getPolylineAccess().getCompositeAssignment_8_0(), "rule__Polyline__CompositeAssignment_8_0");
					put(grammarAccess.getPolylineAccess().getChildrenAssignment_8_1(), "rule__Polyline__ChildrenAssignment_8_1");
					put(grammarAccess.getContainsAccess().getModelReferenceAssignment_1(), "rule__Contains__ModelReferenceAssignment_1");
					put(grammarAccess.getContainsAccess().getConditionalAssignment_2(), "rule__Contains__ConditionalAssignment_2");
					put(grammarAccess.getContainsAccess().getLayoutAssignment_3(), "rule__Contains__LayoutAssignment_3");
					put(grammarAccess.getIntValueAccess().getValueAssignment(), "rule__IntValue__ValueAssignment");
					put(grammarAccess.getDoubleValueAccess().getValueIntAssignment_0(), "rule__DoubleValue__ValueIntAssignment_0");
					put(grammarAccess.getDoubleValueAccess().getValueDecimalAssignment_2(), "rule__DoubleValue__ValueDecimalAssignment_2");
					put(grammarAccess.getStringValueAccess().getNullAssignment_0(), "rule__StringValue__NullAssignment_0");
					put(grammarAccess.getStringValueAccess().getValueAssignment_1(), "rule__StringValue__ValueAssignment_1");
					put(grammarAccess.getBooleanValueAccess().getValueAssignment(), "rule__BooleanValue__ValueAssignment");
					put(grammarAccess.getEnumValueAccess().getNameAssignment(), "rule__EnumValue__NameAssignment");
					put(grammarAccess.getLabelAccess().getEditableAssignment_2(), "rule__Label__EditableAssignment_2");
					put(grammarAccess.getLabelAccess().getStyledAssignment_3_0(), "rule__Label__StyledAssignment_3_0");
					put(grammarAccess.getLabelAccess().getStyleAssignment_3_1(), "rule__Label__StyleAssignment_3_1");
					put(grammarAccess.getLabelAccess().getFeaturesAssignment_5(), "rule__Label__FeaturesAssignment_5");
					put(grammarAccess.getLabelAccess().getCompositeAssignment_6_0(), "rule__Label__CompositeAssignment_6_0");
					put(grammarAccess.getLabelAccess().getChildrenAssignment_6_1(), "rule__Label__ChildrenAssignment_6_1");
					put(grammarAccess.getImageAccess().getImageIdAssignment_1(), "rule__Image__ImageIdAssignment_1");
					put(grammarAccess.getImageAccess().getStyledAssignment_2_0(), "rule__Image__StyledAssignment_2_0");
					put(grammarAccess.getImageAccess().getStyleAssignment_2_1(), "rule__Image__StyleAssignment_2_1");
					put(grammarAccess.getImageAccess().getFeaturesAssignment_4(), "rule__Image__FeaturesAssignment_4");
					put(grammarAccess.getImageAccess().getCompositeAssignment_5_0(), "rule__Image__CompositeAssignment_5_0");
					put(grammarAccess.getImageAccess().getChildrenAssignment_5_1(), "rule__Image__ChildrenAssignment_5_1");
					put(grammarAccess.getInvisibleAccess().getStyledAssignment_2_0(), "rule__Invisible__StyledAssignment_2_0");
					put(grammarAccess.getInvisibleAccess().getStyleAssignment_2_1(), "rule__Invisible__StyleAssignment_2_1");
					put(grammarAccess.getInvisibleAccess().getFeaturesAssignment_4(), "rule__Invisible__FeaturesAssignment_4");
					put(grammarAccess.getInvisibleAccess().getCompositeAssignment_5_0(), "rule__Invisible__CompositeAssignment_5_0");
					put(grammarAccess.getInvisibleAccess().getChildrenAssignment_5_1(), "rule__Invisible__ChildrenAssignment_5_1");
					put(grammarAccess.getForegroundAccess().getTypeAssignment_0(), "rule__Foreground__TypeAssignment_0");
					put(grammarAccess.getForegroundAccess().getColorAssignment_1(), "rule__Foreground__ColorAssignment_1");
					put(grammarAccess.getForegroundAccess().getConditionalAssignment_2(), "rule__Foreground__ConditionalAssignment_2");
					put(grammarAccess.getBackgroundAccess().getTypeAssignment_0(), "rule__Background__TypeAssignment_0");
					put(grammarAccess.getBackgroundAccess().getColorAssignment_1(), "rule__Background__ColorAssignment_1");
					put(grammarAccess.getBackgroundAccess().getConditionalAssignment_2(), "rule__Background__ConditionalAssignment_2");
					put(grammarAccess.getTransparencyAccess().getPercentAssignment_1(), "rule__Transparency__PercentAssignment_1");
					put(grammarAccess.getTransparencyAccess().getConditionalAssignment_2(), "rule__Transparency__ConditionalAssignment_2");
					put(grammarAccess.getSizeAccess().getWidthAssignment_1(), "rule__Size__WidthAssignment_1");
					put(grammarAccess.getSizeAccess().getHeightAssignment_3(), "rule__Size__HeightAssignment_3");
					put(grammarAccess.getSizeAccess().getConditionalAssignment_4(), "rule__Size__ConditionalAssignment_4");
					put(grammarAccess.getPointAccess().getXAssignment_1(), "rule__Point__XAssignment_1");
					put(grammarAccess.getPointAccess().getYAssignment_3(), "rule__Point__YAssignment_3");
					put(grammarAccess.getPointAccess().getConditionalAssignment_4(), "rule__Point__ConditionalAssignment_4");
					put(grammarAccess.getPositionAccess().getXAssignment_1(), "rule__Position__XAssignment_1");
					put(grammarAccess.getPositionAccess().getYAssignment_3(), "rule__Position__YAssignment_3");
					put(grammarAccess.getPositionAccess().getConditionalAssignment_4(), "rule__Position__ConditionalAssignment_4");
					put(grammarAccess.getCornerAccess().getAngleAssignment_1(), "rule__Corner__AngleAssignment_1");
					put(grammarAccess.getCornerAccess().getConditionalAssignment_2(), "rule__Corner__ConditionalAssignment_2");
					put(grammarAccess.getTextValueAccess().getTextAssignment_1_0(), "rule__TextValue__TextAssignment_1_0");
					put(grammarAccess.getTextValueAccess().getModelAttributeAssignment_1_1(), "rule__TextValue__ModelAttributeAssignment_1_1");
					put(grammarAccess.getTextValueAccess().getConditionalAssignment_2(), "rule__TextValue__ConditionalAssignment_2");
					put(grammarAccess.getFontFaceAccess().getFaceAssignment_1(), "rule__FontFace__FaceAssignment_1");
					put(grammarAccess.getFontFaceAccess().getConditionalAssignment_2(), "rule__FontFace__ConditionalAssignment_2");
					put(grammarAccess.getFontSizeAccess().getSizeAssignment_1(), "rule__FontSize__SizeAssignment_1");
					put(grammarAccess.getFontSizeAccess().getConditionalAssignment_2(), "rule__FontSize__ConditionalAssignment_2");
					put(grammarAccess.getFontStyleAccess().getStylesAssignment_1(), "rule__FontStyle__StylesAssignment_1");
					put(grammarAccess.getFontStyleAccess().getStylesAssignment_2_1(), "rule__FontStyle__StylesAssignment_2_1");
					put(grammarAccess.getFontStyleAccess().getConditionalAssignment_3(), "rule__FontStyle__ConditionalAssignment_3");
					put(grammarAccess.getLineStyleAccess().getStyleAssignment_1(), "rule__LineStyle__StyleAssignment_1");
					put(grammarAccess.getLineStyleAccess().getConditionalAssignment_2(), "rule__LineStyle__ConditionalAssignment_2");
					put(grammarAccess.getLineWidthAccess().getWidthAssignment_1(), "rule__LineWidth__WidthAssignment_1");
					put(grammarAccess.getLineWidthAccess().getConditionalAssignment_2(), "rule__LineWidth__ConditionalAssignment_2");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.eclipselabs.xdiagram.ui.contentassist.antlr.internal.InternalDslParser typedParser = (org.eclipselabs.xdiagram.ui.contentassist.antlr.internal.InternalDslParser) parser;
			typedParser.entryRuleXDiagram();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public DslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(DslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
