/*
 * generated by Xtext
 */
package org.eclipselabs.xdiagram.validation;
 
import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.ecore.EPackage;

public class AbstractDslJavaValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.eclipselabs.xdiagram.dsl.DslPackage.eINSTANCE);
		return result;
	}

}
