/**
 * generated by Xtext 2.10.0
 */
package pt.iscte.xdiagram.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import pt.iscte.xdiagram.dsl.ui.AbstractXdiagramDslUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class XdiagramDslUiModule extends AbstractXdiagramDslUiModule {
  public XdiagramDslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
