<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="myDsl" nsURI="http://www.xtext.org/example/mydsl/MyDsl" nsPrefix="myDsl">
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="colors" upperBound="-1"
        eType="#//CustomColor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="images" upperBound="-1"
        eType="#//ImageFile" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//ConnectableElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="links" upperBound="-1"
        eType="#//LinkElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//Feature" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RGB">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="R" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="G" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="B" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImageFile">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="src" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Color">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="custom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rgb" eType="#//CustomColor"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="default" eType="#//DefaultColor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CustomColor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rgb" eType="#//RGB" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DefaultColor">
    <eLiterals name="RED" literal="red"/>
    <eLiterals name="BLUE" value="1" literal="blue"/>
    <eLiterals name="YELLOW" value="2" literal="yellow"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rectangle" eSuperTypes="#//ConnectableElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rectangle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="square" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//AtributeExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rhombus" eSuperTypes="#//ConnectableElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Ellipse" eSuperTypes="#//ConnectableElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ellipse" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="circle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Polygon" eSuperTypes="#//ConnectableElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="polygon" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="polyline" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AtributeExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//AtributeValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AtributeValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueINT" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueDEC" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueBOOL" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueSTRING" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueDAY" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueMONTH" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueYEAR" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Label" eSuperTypes="#//ConnectableElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="editable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Image" eSuperTypes="#//ConnectableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="image" eType="#//ImageFile"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LinkElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lineType" eType="#//LineType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//Feature" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ColorFeature" eSuperTypes="#//Feature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="color" eType="#//Color"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Foreground" eSuperTypes="#//Feature #//ColorFeature"/>
  <eClassifiers xsi:type="ecore:EClass" name="Background" eSuperTypes="#//Feature #//ColorFeature"/>
  <eClassifiers xsi:type="ecore:EClass" name="Border" eSuperTypes="#//ColorFeature"/>
  <eClassifiers xsi:type="ecore:EClass" name="Transparency" eSuperTypes="#//Feature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="percent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Size" eSuperTypes="#//Feature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Point" eSuperTypes="#//Feature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Position" eSuperTypes="#//Feature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Corner" eSuperTypes="#//Feature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="angle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FontFace" eSuperTypes="#//Feature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="face" eType="#//FontFaceType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FontSize" eSuperTypes="#//Feature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FontStyle" eSuperTypes="#//Feature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="styles" unique="false"
        upperBound="-1" eType="#//FontStyleType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FontFaceType">
    <eLiterals name="ARIAL" literal="arial"/>
    <eLiterals name="VERDANA" value="1" literal="verdana"/>
    <eLiterals name="TIMES" value="2" literal="times"/>
    <eLiterals name="COURIER" value="3" literal="courier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FontStyleType">
    <eLiterals name="ITALICS" literal="italics"/>
    <eLiterals name="BOLD" value="1" literal="bold"/>
    <eLiterals name="UNDERLINE" value="2" literal="underline"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LineStyle" eSuperTypes="#//Feature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="style" eType="#//LineType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LineType">
    <eLiterals name="SOLID" literal="solid"/>
    <eLiterals name="DASH" value="1" literal="dash"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LineWidth" eSuperTypes="#//Feature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
