/*
 * generated by Xtext
 */
package org.eclipselabs.xdiagram.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class XDiagramUiModule extends org.eclipselabs.xdiagram.xtext.ui.AbstractXDiagramUiModule {
	public XDiagramUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
