/**
 *
 * $Id$
 */
package featuremodel.validation;

import featuremodel.AbstractFeature;
import featuremodel.Constraint;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link featuremodel.Feature}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FeatureValidator {
	boolean validate();

	boolean validateOptional(boolean value);
	boolean validateConstraints(EList<Constraint> value);
	boolean validateParent(AbstractFeature value);
}
