/**
 * generated by Xtext 2.10.0
 */
package pt.iscte.xdiagram.dsl.ui.contentassist;

import pt.iscte.xdiagram.dsl.ui.contentassist.AbstractXdiagramDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class XdiagramDslProposalProvider extends AbstractXdiagramDslProposalProvider {
}
