/**
 * generated by Xtext 2.10.0
 */
package pt.iscte.xdiagram.dsl.model.impl;

import org.eclipse.emf.ecore.EClass;

import pt.iscte.xdiagram.dsl.model.ModelPackage;
import pt.iscte.xdiagram.dsl.model.Rhombus;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Rhombus</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class RhombusImpl extends ConnectableElementImpl implements Rhombus
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RhombusImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ModelPackage.Literals.RHOMBUS;
  }

} //RhombusImpl
